---
language: ruby
matrix:
  fast_finish: true
  include:
  - rvm: '2.1'
    sudo: required
    services: docker
    env: SUITE=centos-7-docker
    script:
      - bundle exec rake acceptance:suite_on_nodeset['centos-7-docker']
  - rvm: '2.1'
    sudo: required
    services: docker
    env: SUITE=debian-8-docker
    script:
      - bundle exec rake acceptance:suite_on_nodeset['debian-8-docker']
  - rvm: '2.1'
    sudo: required
    services: docker
    env: SUITE=ubuntu-1604-docker
    script:
      - bundle exec rake acceptance:suite_on_nodeset['ubuntu-1604-docker']
